<a href="https://colab.research.google.com/github/AmanyaPhillip/Data-Analyst-Mental-Health-Project/blob/main/perceived_health.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_csv("/content/perceived_health_quarterly.csv")
df.head()

,ref_date_raw,start_year,geo,sex,indicator,value,metric_type,quality_flag,scalar_applied,vector,ref_date,dguid,statistic,uom,scalar_factor
0,2021-04,2021,Canada (excluding territories),"Total, all persons",Excellent or very good perceived health,57.1,percent,NaN,False,v1427746919,2021-04,2016A000011124,Percentage of persons,Percent,units
1,2021-04,2021,Canada (excluding territories),"Total, all persons",Excellent or very good perceived health,55.9,percent,NaN,False,v1427746920,2021-04,2016A000011124,"Lower bound of the 95% confidence interval, pe...",Percent,units
2,2021-04,2021,Canada (excluding territories),"Total, all persons",Excellent or very good perceived health,58.4,percent,NaN,False,v1427746921,2021-04,2016A000011124,"Upper bound of the 95% confidence interval, pe...",Percent,units
3,2021-04,2021,Canada (excluding territories),"Total, all persons",Excellent or very good perceived health,17877000.0,number,NaN,True,v1427746922,2021-04,2016A000011124,Number of persons,Number,thousands
4,2021-04,2021,Canada (excluding territories),"Total, all persons",Excellent or very good perceived health,17492000.0,number,NaN,True,v1427746923,2021-04,2016A000011124,"Lower bound of the 95% confidence interval, nu...",Number,thousands

In [2]:
#Finding number of rows and coulumns
df.shape

(6318, 15)

In [3]:
# Checking dandom samples
df.sample(5)

,ref_date_raw,start_year,geo,sex,indicator,value,metric_type,quality_flag,scalar_applied,vector,ref_date,dguid,statistic,uom,scalar_factor
537,2021-04,2021,Manitoba,Women,Fair or poor perceived health,NaN,number,f,True,v1427747456,2021-04,2016A000246,Number of persons,Number,thousands
2116,2022-01,2022,Canada (excluding territories),"Total, all persons",Good perceived health,10005000.0,number,NaN,True,v1427746929,2022-01,2016A000011124,"Lower bound of the 95% confidence interval, nu...",Number,thousands
3101,2022-04,2022,New Brunswick,Men,Excellent or very good perceived health,164000.0,number,e,True,v1427747212,2022-04,2016A000213,"Upper bound of the 95% confidence interval, nu...",Number,thousands
666,2021-04,2021,British Columbia,Men,Excellent or very good perceived health,58.5,percent,NaN,False,v1427747585,2021-04,2016A000259,Percentage of persons,Percent,units
5386,2023-04,2023,Prairies Region,Women,Excellent or very good perceived health,1240000.0,number,NaN,True,v1427747391,2023-04,2016A00014,"Lower bound of the 95% confidence interval, nu...",Number,thousands

In [4]:
# Verifying columns names are loaded
df.columns

Index(['ref_date_raw', 'start_year', 'geo', 'sex', 'indicator', 'value',
       'metric_type', 'quality_flag', 'scalar_applied', 'vector', 'ref_date',
       'dguid', 'statistic', 'uom', 'scalar_factor'],
      dtype='object')

In [5]:
# Check for Data types
df.dtypes

ref_date_raw       object
start_year          int64
geo                object
sex                object
indicator          object
value             float64
metric_type        object
quality_flag       object
scalar_applied       bool
vector             object
ref_date           object
dguid              object
statistic          object
uom                object
scalar_factor      object
dtype: object

In [6]:
#Check for any duplicates
duplicates = df.duplicated().sum()
print(duplicates)

0

In [7]:
# Check for any missing values
missing_values = df.isnull().sum()
print(missing_values)

ref_date_raw         0
start_year           0
geo                  0
sex                  0
indicator            0
value              345
metric_type          0
quality_flag      5211
scalar_applied       0
vector               0
ref_date             0
dguid                0
statistic            0
uom                  0
scalar_factor        0
dtype: int64

### Handling Missing Values

I'll fill missing values in `quality_flag` with 'No Flag' and `value` with its median.

In [10]:
# Fill missing values in 'quality_flag' with 'No Flag'
df['quality_flag'] = df['quality_flag'].fillna('No Flag')

# Fill missing values in 'value' with the median
median_value = df['value'].median()
df['value'] = df['value'].fillna(median_value)

In [11]:
# Verify that missing values have been handled
missing_values_after_handling = df.isnull().sum()
print(missing_values_after_handling)

ref_date_raw      0
start_year        0
geo               0
sex               0
indicator         0
value             0
metric_type       0
quality_flag      0
scalar_applied    0
vector            0
ref_date          0
dguid             0
statistic         0
uom               0
scalar_factor     0
dtype: int64

In [12]:
df.head()

,ref_date_raw,start_year,geo,sex,indicator,value,metric_type,quality_flag,scalar_applied,vector,ref_date,dguid,statistic,uom,scalar_factor
0,2021-04,2021,Canada (excluding territories),"Total, all persons",Excellent or very good perceived health,57.1,percent,No Flag,False,v1427746919,2021-04,2016A000011124,Percentage of persons,Percent,units
1,2021-04,2021,Canada (excluding territories),"Total, all persons",Excellent or very good perceived health,55.9,percent,No Flag,False,v1427746920,2021-04,2016A000011124,"Lower bound of the 95% confidence interval, pe...",Percent,units
2,2021-04,2021,Canada (excluding territories),"Total, all persons",Excellent or very good perceived health,58.4,percent,No Flag,False,v1427746921,2021-04,2016A000011124,"Upper bound of the 95% confidence interval, pe...",Percent,units
3,2021-04,2021,Canada (excluding territories),"Total, all persons",Excellent or very good perceived health,17877000.0,number,No Flag,True,v1427746922,2021-04,2016A000011124,Number of persons,Number,thousands
4,2021-04,2021,Canada (excluding territories),"Total, all persons",Excellent or very good perceived health,17492000.0,number,No Flag,True,v1427746923,2021-04,2016A000011124,"Lower bound of the 95% confidence interval, nu...",Number,thousands

In [16]:
df.tail()

,ref_date_raw,start_year,geo,sex,indicator,value,metric_type,quality_flag,scalar_applied,vector,ref_date,dguid,statistic,uom,scalar_factor
6313,2023-07,2023,British Columbia,Women,Fair or poor perceived health,15.9,percent,No Flag,False,v1427747616,2023-07,2016A000259,"Lower bound of the 95% confidence interval, pe...",Percent,units
6314,2023-07,2023,British Columbia,Women,Fair or poor perceived health,24.5,percent,No Flag,False,v1427747617,2023-07,2016A000259,"Upper bound of the 95% confidence interval, pe...",Percent,units
6315,2023-07,2023,British Columbia,Women,Fair or poor perceived health,455000.0,number,e,True,v1427747618,2023-07,2016A000259,Number of persons,Number,thousands
6316,2023-07,2023,British Columbia,Women,Fair or poor perceived health,356000.0,number,e,True,v1427747619,2023-07,2016A000259,"Lower bound of the 95% confidence interval, nu...",Number,thousands
6317,2023-07,2023,British Columbia,Women,Fair or poor perceived health,554000.0,number,e,True,v1427747620,2023-07,2016A000259,"Upper bound of the 95% confidence interval, nu...",Number,thousands

In [19]:
# Save the cleaned dataset
df.to_csv('cleaned_data.csv', index=False)